name: MD to HTML
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '/**.md'
      - '/media/**'

jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: /
          output_dir: /
          images_dir: /media
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: true
          build_pdf: false
      - uses: actions/upload-artifact@v3
        with:
          name: html
          path: /
